spring:
  application:
    name: library-event-producer
  profiles:
    active: local
    kafka:
      producer:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
        key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

